### ISSUE TITLE
Can we support version v2.4.7?

### ISSUE THREAD

**Issue by ifilonenko** [conda-forge/pyspark-feedstock#29]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by harpaj** [comment]
We would also be interested in this, particularly for version 3.0.3.
According to https://conda-forge.org/docs/maintainer/updating_pkgs.html#maintaining-several-versions, it's possible rather easily, but it has to be done by a maintainer with permissions to create additional branches in this repo.

**Comment by j-4** [comment]
@harpaj v3.0.3 is tackled in https://github.com/conda-forge/pyspark-feedstock/pull/38

@ifilonenko is v2.4.8 sufficient for you? It is tackled in https://github.com/conda-forge/pyspark-feedstock/pull/39 If not, we would need to build 2.4.7 first and then add the update to 2.4.8 later.

**Comment by j-4** [comment]
I decided to also package 2.4.7 and then upgrade to 2.4.8 as CDH7.1 depends still on 2.4.7, thus I guess many people would love to have 2.4.7 for testing purposes and such. Thus this issue is tackled in https://github.com/conda-forge/pyspark-feedstock/pull/40

**Comment by dbast** [comment]
@j-4 Thanks!
