### ISSUE TITLE
Configuring log4j.properties

### ISSUE THREAD

**Issue by nickray** [conda-forge/pyspark-feedstock#7]
I would like to minimise logging output.
Where is the config file supposed to be located?
It would be good to include a default file or at least `log4j.properties.template`.

**Comment by zero323** [comment]
@nickray This project depends on upstream PySpark distribution files, which don't include configuration templates. 

If you want to provide your own configuration, you can start with [upstream templates](https://github.com/apache/spark/tree/master/conf) and use `SPARK_CONF_DIR` environment variable to indicate directory where Spark should check for configuration (see [overriding configuration directory](https://spark.apache.org/docs/latest/configuration.html#overriding-configuration-directory) in the official documentation).
